### PR TITLE
Fixed Pep8 issues.

### PR DESCRIPTION
**Pull request by nnDarshan**
I ran pep8 test on all .py files in the project and fixed the issues reported by it.

Signed-off-by: nnDarshan <darshan.n.2024@gmail.com>

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="https://app.review.ninja/Tendrl/ceph_bridge/pull/4" target="_blank">ReviewNinja

**Comment by r0h4n** [comment]
"tox -epep8" still seems to be failing in the TravisCI build, please fix the failures

details: https://travis-ci.org/Tendrl/ceph_bridge/builds/154730363

**Comment by nnDarshan** [comment]
Well the pep8 errors are fixed in this patch. The TravisCI must be checking for some other style guide. I feel those can be fixed as a separate patch.

**Comment by r0h4n** [comment]
Please fix all failures when running "tox -epep8", Tendrl has its own style checks which are part of the PEP8 checks for Tendrl

**Pull request merged**
